install.packages("jsonlite")
install.packages("DirichletReg")
install.packages("matrixStats")
install.packages("Rcpp")
install.packages("RcppGSL")

#Here is all the packages that you have download one by one
#install.packages("stats19_2.0.0.tar.gz")
#install.packages("zoo_1.8-9.tar.gz")
#install.packages("digest_0.6.28.tar.gz")
#install.packages("Formula_1.2-4.tar.gz")
#install.packages("Rcpp_1.0.7.tar.gz")
#install.packages("Rcpp11_3.1.2.0.1.tar.gz")
#install.packages("RcppGSL_0.3.10.tar.gz")
#install.packages("jsonlite_1.7.2.tar.gz")
#install.packages("generics_0.1.1.tar.gz")
#install.packages("miscTools_0.6-26.tar.gz")
#install.packages("sandwich_3.0-1.tar.gz")
#install.packages("maxLik_1.5-2.tar.gz")
#install.packages("matrixStats_0.61.0.tar.gz")
#install.packages("DirichletReg_0.7-1.tar.gz")